export const beaches = [
  {
    type: "Feature",
    id: 90,
    geometry: { type: "Point", coordinates: [44.485685, 34.160379] },
    name: "Пляж",
    description: "Ялта, Республика Крым",
    link: "https://пляжиялты.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 91,
    geometry: { type: "Point", coordinates: [44.47834, 34.157539] },
    name: "Пляж",
    description: "Ялта, Республика Крым",
    link: "https://пляжиялты.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 92,
    geometry: { type: "Point", coordinates: [44.483997, 34.159507] },
    name: "Пляж",
    description: "Ялта, Республика Крым",
    link: "https://пляжиялты.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Гагаринский пляж",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 93,
    geometry: { type: "Point", coordinates: [44.476629, 34.156208] },
    name: "Пляж Дельфин",
    description: "Ялта, Республика Крым",
    link: "https://дельфин.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж Дельфин",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 94,
    geometry: { type: "Point", coordinates: [44.486233, 34.160662] },
    name: "Пляж Опера Прима",
    description: "Ялта, Республика Крым",
    link: "https://пляжопераприма.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Опера Прима",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 95,
    geometry: { type: "Point", coordinates: [44.496654, 34.175053] },
    name: "Пляж Гороно",
    description: "Ялта, Республика Крым",
    link: "https://пляжиялты.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж Гороно",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 96,
    geometry: { type: "Point", coordinates: [44.49761, 34.178867] },
    name: "Эйфелева башня",
    description: "Ялта, Республика Крым",
    link: "https://эйфелевабашня.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Эйфелева башня",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 97,
    geometry: { type: "Point", coordinates: [44.500291, 34.191074] },
    name: "Ялта-Интурист",
    description: "Ялта, Республика Крым",
    link: "https://пляжаялтаинтурист.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Ялта-Интурист",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 98,
    geometry: {
      type: "Point",
      coordinates: [44.49850531440116, 34.18157493408945],
    },
    name: "Пляж Ковер",
    description: "Ялта, Республика Крым",
    link: "https://пляжковер.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж Ковер",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 99,
    geometry: { type: "Point", coordinates: [44.458849, 34.144405] },
    name: "Пляж Ореанда",
    description: "Ялта, Республика Крым",
    link: "https://пляжореанда.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж Ореанда",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 100,
    geometry: {
      type: "Point",
      coordinates: [44.49995189954835, 34.195331284686766],
    },
    name: "Пляж Донбасс",
    description: "Ялта, Республика Крым",
    link: "https://пляждонбасс.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж Донбасс",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 101,
    geometry: {
      type: "Point",
      coordinates: [44.47319090463763, 34.1521556964033],
    },
    name: "Пляж Черноморье",
    description: "Ялта, Республика Крым",
    link: "https://пляжчерноморье.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж Черноморье",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 102,
    geometry: { type: "Point", coordinates: [44.484508, 34.159746] },
    name: "Пляж Левант",
    description: "Ялта, Республика Крым",
    link: "https://пляжлевант.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Левант",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 103,
    geometry: { type: "Point", coordinates: [44.503476, 34.211982] },
    name: "Пляж",
    description: "Ялта, Республика Крым",
    link: "https://пляжиялты.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 104,
    geometry: { type: "Point", coordinates: [44.480771, 34.158365] },
    name: "Пляж",
    description: "Ялта, Республика Крым",
    link: "https://пляжиялты.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 105,
    geometry: { type: "Point", coordinates: [44.499215, 34.183731] },
    name: "Пляж Актер",
    description: "Ялта, Республика Крым",
    link: "https://пляжактер.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж Актер",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 106,
    geometry: { type: "Point", coordinates: [44.500007, 34.188408] },
    name: "Пляж",
    description: "Ялта, Республика Крым",
    link: "https://пляжиялты.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 107,
    geometry: { type: "Point", coordinates: [44.485093, 34.160035] },
    name: "Пляж",
    description: "Ялта, Республика Крым",
    link: "https://пляжиялты.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 108,
    geometry: { type: "Point", coordinates: [44.479876, 34.158148] },
    name: "Пляж",
    description: "Ялта, Республика Крым",
    link: "https://пляжиялты.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж ",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 109,
    geometry: { type: "Point", coordinates: [44.479444, 34.158043] },
    name: "Пляж",
    description: "Ялта, Республика Крым",
    link: "https://пляжиялты.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 110,
    geometry: { type: "Point", coordinates: [44.487525, 34.161501] },
    name: "Приморский пляж",
    description: "Ялта, Республика Крым",
    link: "https://пляжиялты.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Приморский пляж",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 111,
    geometry: { type: "Point", coordinates: [44.489945, 34.163487] },
    name: "Приморский пляж",
    description: "Ялта, Республика Крым",
    link: "https://пляжиялты.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 112,
    geometry: { type: "Point", coordinates: [44.482966, 34.159266] },
    name: "Пляж Лотос",
    description: "Ялта, Республика Крым",
    link: "https://пляжиялты.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж Лотос",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 113,
    geometry: { type: "Point", coordinates: [44.46753, 34.149472] },
    name: "Пляж Ливадия",
    description: "Ялта, Республика Крым",
    link: "https://пляжливадия.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж Ливадия",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 114,
    geometry: { type: "Point", coordinates: [44.497409, 34.176962] },
    name: "Пляж Массандра",
    description: "Ялта, Республика Крым",
    link: "https://пляжмассандра.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Пляж Массандра",
      "marker-color": "#177bc9",
    },
  },
];
