export const cities = [
  {
    type: "Feature",
    id: 6,
    geometry: { type: "Point", coordinates: [44.544691, 34.284347] },
    name: "Гурзуф",
    description: "посёлок городского типа Гурзуф",
    link: "https://гурзуф.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Гурзуф",
      "marker-color": "#82cdff",
    },
  },
  {
    type: "Feature",
    id: 7,
    geometry: { type: "Point", coordinates: [44.391772, 33.78747] },
    name: "Форос",
    description: "посёлок городского типа Форос",
    link: "https://форос.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Форос",
      "marker-color": "#82cdff",
    },
  },
  {
    type: "Feature",
    id: 8,
    geometry: { type: "Point", coordinates: [44.427722, 34.083537] },
    name: "Кореиз",
    description: "посёлок городского типа Кореиз",
    link: "https://кореиз.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Кореиз",
      "marker-color": "#82cdff",
    },
  },
  {
    type: "Feature",
    id: 9,
    geometry: { type: "Point", coordinates: [44.410429, 33.867789] },
    name: "Олива",
    description: "посёлок Олива",
    link: "https://олива.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Олива",
      "marker-color": "#82cdff",
    },
  },
  {
    type: "Feature",
    id: 10,
    geometry: { type: "Point", coordinates: [44.421239, 34.053462] },
    name: "Алупка",
    description: "Алупка, городской округ Ялта",
    link: "https://алупка.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Алупка",
      "marker-color": "#82cdff",
    },
  },
  {
    type: "Feature",
    id: 11,
    geometry: { type: "Point", coordinates: [44.409006, 33.941235] },
    name: "Оползневое",
    description: "село на южном берегу Крыма",
    link: "https://оползневое.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Оползневое",
      "marker-color": "#82cdff",
    },
  },
  {
    type: "Feature",
    id: 12,
    geometry: { type: "Point", coordinates: [44.416108, 33.984884] },
    name: "Голубой Залив",
    description: "посёлок городского типа Симеиз",
    link: "https://голубойзаливсимеиз.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Голубой Залив",
      "marker-color": "#82cdff",
    },
  },
  {
    type: "Feature",
    id: 13,
    geometry: { type: "Point", coordinates: [44.470205, 34.069137] },
    name: "Охотничье",
    description: "городской округ Ялта, посёлок Охотничье",
    link: "https://охотничье.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Охотничье",
      "marker-color": "#82cdff",
    },
  },
  {
    type: "Feature",
    id: 14,
    geometry: { type: "Point", coordinates: [44.405413, 33.892528] },
    name: "Береговое",
    description: "посёлок городского типа Береговое",
    link: "https://береговое.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Береговое",
      "marker-color": "#82cdff",
    },
  },
  {
    type: "Feature",
    id: 15,
    geometry: { type: "Point", coordinates: [44.393414, 33.972047] },
    name: "Кацивели",
    description: "посёлок городского типа Кацивели",
    link: "https://кацивели.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Кацивели",
      "marker-color": "#82cdff",
    },
  },
  {
    type: "Feature",
    id: 16,
    geometry: { type: "Point", coordinates: [44.406675, 34.00542] },
    name: "Симеиз",
    description: "посёлок городского типа Симеиз",
    link: "https://симеиз.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Симеиз",
      "marker-color": "#82cdff",
    },
  },
  {
    type: "Feature",
    id: 17,
    geometry: { type: "Point", coordinates: [44.430252, 34.10577] },
    name: "Гаспра",
    description: "посёлок городского типа Гаспра",
    link: "https://гаспра.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Гаспра",
      "marker-color": "#82cdff",
    },
  },
];
