export const observe = [
  {
    type: "Feature",
    id: 100,
    geometry: { type: "Point", coordinates: [44.478236, 34.141062] },
    name: "Смотровая площадка",
    description: "Ялта, посёлок городского типа Ливадия",
    link: "https://смотровыеялта.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Вид на Ялту",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 101,
    geometry: { type: "Point", coordinates: [44.498368, 34.160883] },
    name: "Смотровая площадка",
    description: "Ялта, Республика Крым",
    link: "https://смотровыеялта.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Смотровая площадка",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 102,
    geometry: { type: "Point", coordinates: [44.514784, 34.186401] },
    name: "Смотровая площадка",
    description: "Ялта, Республика Крым",
    link: "https://смотровыеялта.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Смотровая площадка",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 103,
    geometry: { type: "Point", coordinates: [44.475605, 34.138156] },
    name: "Смотровая площадка",
    description: "Ялта, Республика Крым",
    link: "https://смотровыеялта.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Смотровая площадка",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 104,
    geometry: { type: "Point", coordinates: [44.500039, 34.177147] },
    name: "Смотровая площадка",
    description: "Ялта, Республика Крым",
    link: "https://смотровыеялта.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Смотровая площадка",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 105,
    geometry: { type: "Point", coordinates: [44.516793, 34.202847] },
    name: "Смотровая площадка",
    description: "Ялта, Республика Крым",
    link: "https://смотровыеялта.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Смотровая площадка",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 106,
    geometry: { type: "Point", coordinates: [44.493401, 34.165382] },
    name: "Смотровая площадка",
    description: "Ялта, Республика Крым",
    link: "https://смотровыеялта.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Смотровая площадка",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 107,
    geometry: { type: "Point", coordinates: [44.500039, 34.177147] },
    name: "Смотровая площадка",
    description: "Ялта, Республика Крым",
    link: "https://смотровыеялта.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Смотровая площадка",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 108,
    geometry: { type: "Point", coordinates: [44.514784, 34.186401] },
    name: "Смотровая площадка",
    description: "Ялта, Республика Крым",
    link: "https://смотровыеялта.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Смотровая площадка",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 109,
    geometry: { type: "Point", coordinates: [44.459592, 34.142717] },
    name: "Смотровая площадка",
    description: "Ялта, Республика Крым",
    link: "https://смотровыеялта.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Смотровая площадка",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 110,
    geometry: { type: "Point", coordinates: [44.493401, 34.165382] },
    name: "Смотровая площадка",
    description: "Ялта, Республика Крым",
    link: "https://смотровыеялта.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Смотровая площадка",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 111,
    geometry: { type: "Point", coordinates: [44.457698, 34.138215] },
    name: "Смотровая площадка",
    description: "Ялта, Республика Крым",
    link: "https://смотровыеялта.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Смотровая площадка",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 112,
    geometry: { type: "Point", coordinates: [44.485501, 34.158325] },
    name: "Смотровая площадка",
    description: "Ялта, Республика Крым",
    link: "https://смотровыеялта.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Смотровая площадка",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 113,
    geometry: { type: "Point", coordinates: [44.452486, 34.126825] },
    name: "Смотровая площадка",
    description: "Ялта, Республика Крым",
    link: "https://смотровыеялта.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Смотровая площадка",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 114,
    geometry: {
      type: "Point",
      coordinates: [44.50952331820683, 34.18553387459542],
    },
    name: "Смотровая Беседка",
    description: "Ялта, Республика Крым",
    link: "https://смотровыеялта.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Смотровая Беседка",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 115,
    geometry: { type: "Point", coordinates: [44.486377, 34.078203] },
    name: "Смотровая площадка Таракташ",
    description: "Ялта, Республика Крым",
    link: "https://таракташ.гидпокрыму.online/",
    buttonText: "Узнать больше",
    properties: {
      description: "",
      iconCaption: "Смотровая площадка Таракташ",
      "marker-color": "#1bad03",
    },
  },
];
