export const points = [
  {
    type: "Feature",
    id: 21,
    name: "CapeHostel",
    description: "Капсульный отель в самом сердце Cевастополя",
    link: "https://reservationsteps.ru/rooms/index/c06872fc-9daa-415f-a0e3-7fbf0363cfcb",
    buttonText: "Забронировать online",
    geometry: { type: "Point", coordinates: [44.605935, 33.521711] },
    properties: {
      description: "",
      iconCaption: "CapeHostel",
      "marker-color": "#0e4779",
    },
  },
  {
    type: "Feature",
    id: 22,
    name: "Джанкойский район",
    description: "Джанкойский район, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [45.794086, 34.436863] },
    properties: {
      description: "",
      iconCaption: "Джанкойский район",
      "marker-color": "#e6761b",
    },
  },
  {
    type: "Feature",
    id: 23,
    name: "Красноперекопский район",
    description: "Красноперекопский район, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [45.993498, 33.828254] },
    properties: {
      description: "",
      iconCaption: "Красноперекопский район",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 24,
    name: "городской округ Армянск",
    description: "городской округ Армянск, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: {
      type: "Point",
      coordinates: [46.13367327358061, 33.68781251138779],
    },
    properties: {
      description: "",
      iconCaption: "городской округ Армянск",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 25,
    name: "Раздольненский район",
    description: "Раздольненский район, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [45.700024, 33.377407] },
    properties: {
      description: "",
      iconCaption: "Раздольненский район",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 26,
    name: "Красногвардейский район",
    description: "Красногвардейский район, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [45.401947, 34.254531] },
    properties: {
      description: "",
      iconCaption: "Красногвардейский район",
      "marker-color": "#e6761b",
    },
  },
  {
    type: "Feature",
    id: 27,
    name: "Первомайский район",
    description: "Первомайский район, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [45.59821, 33.832476] },
    properties: {
      description: "",
      iconCaption: "Первомайский район",
      "marker-color": "#e6761b",
    },
  },
  {
    type: "Feature",
    id: 28,
    name: "Черноморский район",
    description: "Черноморский район, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [45.477437, 32.770021] },
    properties: {
      description: "",
      iconCaption: "Черноморский район",
      "marker-color": "#177bc9",
    },
  },
  {
    type: "Feature",
    id: 29,
    name: "Сакский район",
    description: "Сакский район, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [45.27848, 33.510798] },
    properties: {
      description: "",
      iconCaption: "Сакский район",
      "marker-color": "#1e98ff",
    },
  },
  {
    type: "Feature",
    id: 30,
    name: "Бахчисарайский район",
    description: "Бахчисарайский район, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [44.710282, 33.898475] },
    properties: {
      description: "",
      iconCaption: "Бахчисарайский район",
      "marker-color": "#ed4543",
    },
  },
  {
    type: "Feature",
    id: 31,
    name: "Симферопольский район",
    description: "Симферопольский район, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [44.984154, 34.036798] },
    properties: {
      description: "",
      iconCaption: "Симферопольский район",
      "marker-color": "#ed4543",
    },
  },
  {
    type: "Feature",
    id: 32,
    name: "городской округ Ялта",
    description: "городской округ Ялта, Республика Крым",
    link: "https://округялта.гидпокрыму.online/",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [44.450293, 34.063253] },
    properties: {
      description: "",
      iconCaption: "городской округ Ялта",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 33,
    name: "городской округ Алушта",
    description: "городской округ Алушта, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [44.759285, 34.462932] },
    properties: {
      description: "",
      iconCaption: "городской округ Алушта",
      "marker-color": "#56db40",
    },
  },
  {
    type: "Feature",
    id: 34,
    name: "Белогорский район",
    description: "Белогорский район, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [45.063037, 34.556716] },
    properties: {
      description: "",
      iconCaption: "Белогорский район",
      "marker-color": "#e6761b",
    },
  },
  {
    type: "Feature",
    id: 35,
    name: "Кировский район",
    description: "Кировский район, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [45.122309, 35.180308] },
    properties: {
      description: "",
      iconCaption: "Кировский район",
      "marker-color": "#ff931e",
    },
  },
  {
    type: "Feature",
    id: 36,
    name: "городской округ Судак",
    description: "городской округ Судак, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [44.906655, 34.949738] },
    properties: {
      description: "",
      iconCaption: "городской округ Судак",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 37,
    name: "Советский район",
    description: "Советский район, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [45.371462, 34.924252] },
    properties: {
      description: "",
      iconCaption: "Советский район",
      "marker-color": "#ff931e",
    },
  },
  {
    type: "Feature",
    id: 38,
    name: "городской округ Феодосия",
    description: "городской округ Феодосия, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [45.00912, 35.320113] },
    properties: {
      description: "",
      iconCaption: "городской округ Феодосия",
      "marker-color": "#56db40",
    },
  },
  {
    type: "Feature",
    id: 39,
    name: "Ленинский район",
    description: "Ленинский район, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [45.264975, 36.038127] },
    properties: {
      description: "",
      iconCaption: "Ленинский район",
      "marker-color": "#1bad03",
    },
  },
  {
    type: "Feature",
    id: 40,
    name: "городской округ Керчь",
    description: "городской округ Керчь, Республика Крым",
    link: "",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [45.346351, 36.45305] },
    properties: {
      description: "",
      iconCaption: "городской округ Керчь",
      "marker-color": "#e6761b",
    },
  },
  {
    type: "Feature",
    id: 41,
    name: "Севастополь",
    description: "Город федерального значения, Республика Крым",
    link: "https://севастополь.гидпокрыму.online/",
    buttonText: "Узнать больше",
    geometry: { type: "Point", coordinates: [44.556972, 33.526402] },
    properties: {
      description: "",
      iconCaption: "Севастополь",
      "marker-color": "#1e98ff",
    },
  },
];
